# Generated by Django 5.0.3 on 2024-03-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='name',
            new_name='title',
        ),
    ]
